[versions]
kotlin = "2.2.21"                # https://github.com/JetBrains/kotlin
coroutines = "1.10.2"            # https://github.com/Kotlin/kotlinx.coroutines
detekt = "1.23.8"                # https://github.com/detekt/detekt
dokka = "2.1.0"                  # https://github.com/Kotlin/dokka
spotless = "8.0.0"               # https://github.com/diffplug/spotless
dependency = "1.33.0"            # https://github.com/autonomousapps/dependency-analysis-gradle-plugin
pitest = "1.15.0"                # https://plugins.gradle.org/plugin/info.solidsoft.pitest | https://search.maven.org/artifact/org.pitest/pitest
pinterestKtlint = "0.51.0-FINAL" # https://github.com/pinterest/ktlint
ktlint = "13.1.0"                # https://github.com/JLLeitschuh/ktlint-gradle
kover = "0.9.3"                  # https://github.com/Kotlin/kotlinx-kover
diktat = "2.0.0"                 # https://github.com/saveourtool/diktat
serialization = "1.9.0"          # https://github.com/Kotlin/kotlinx.serialization

# --- Serialization ---
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# --- Networking & Serialization ---
retrofit = "3.0.0"               # https://github.com/square/retrofit
okhttp = "5.2.1"                 # https://square.github.io/okhttp/changelogs/changelog
sandwich = "2.1.3"               # https://github.com/skydoves/sandwich
protobufPlugin = "0.9.5"         # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-gradle-plugin
protobufKotlin = "4.32.0"        # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-kotlin
protoc = "4.32.0"                # https://mvnrepository.com/artifact/com.google.protobuf/protoc
jsoup = "1.21.2"                 # https://jsoup.org/

# --- Testing ---
junit = "6.0.1"                  # https://junit.org/junit5 | https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter
kotest = "5.9.1"                 # https://kotest.io
kotlintest = "3.4.2"             # https://mvnrepository.com/artifact/io.kotlintest/kotlintest-core
assertj = "3.27.6"               # https://mvnrepository.com/artifact/org.assertj/assertj-core | https://assertj.github.io/doc
mockito = "5.20.0"               # https://mvnrepository.com/artifact/org.mockito/mockito-core
mockitoKotlin2 = "2.2.0"         # https://mvnrepository.com/artifact/com.nhaarman.mockitokotlin2/mockito-kotlin
mockitoKotlin = "6.1.0"          # https://github.com/mockito/mockito-kotlin
mockk = "1.14.6"                 # https://mockk.io | https://central.sonatype.com/search?q=mockk&smo=true
hamcrest = "3.0"                 # https://hamcrest.org
turbine = "1.2.1"                # https://github.com/cashapp/turbine/releases
truth = "1.4.5"                  # https://central.sonatype.com/artifact/com.google.truth/truth/overview
lincheck = "2.39"                # https://github.com/JetBrains/lincheck

[libraries]
# --- Kotlin & Core ---
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
pinterestKtlint = { module = "com.pinterest:ktlint", version.ref = "pinterestKtlint" }

# --- Coroutines ---
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlin-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# --- Networking ---
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
sandwich-retrofit = { group = "com.github.skydoves", name = "sandwich-retrofit", version.ref = "sandwich" }

# --- Testing Tools ---
lincheck = { module = "org.jetbrains.kotlinx:lincheck", version.ref = "lincheck" }

# --- Testing Libraries ---
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlintest-core = { module = "io.kotlintest:kotlintest-core", version.ref = "kotlintest" }
kotlintest-junit5 = { module = "io.kotlintest:kotlintest-runner-junit5", version.ref = "kotlintest" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin2 = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin2" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
kt-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency" }
pitest = { id = "info.solidsoft.pitest", version.ref = "pitest" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
diktat = { id = "com.saveourtool.diktat", version.ref = "diktat" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
